SECRET_KEY = "APA"

# MongoDB
MONGODB_CONNECTION_STRING = "#"
MONGODB_DATABASE_NAME = "master-menpro"
MONGODB_COLLECTION_PRODUCTS = "master_product"
MONGODB_COLLECTION_PRODUCTS_COME = "master_supplier"
MONGODB_COLLECTION_PRODUCTS_OUT = "master_supplier_out"
MONGODB_COLLECTION_USER = "master_karyawan"

# Auth DB
MONGO_AUTH_DATABASE = "auth_db"
MONGODB_COLLECTION_SESSIONS = "sessions" 